stages:
#  - test
#  - analyze
  - build
  - create_version
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -e -V"

# Only run this pipeline when MR is merged into main
workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'  # For MR pipelines
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

#test:
#  stage: test
#  image: maven:3.9.4-eclipse-temurin-17
#  script:
#    - mvn $MAVEN_CLI_OPTS test

#code_analysis:
#  stage: analyze
#  image: maven:3.9.4-eclipse-temurin-17
#  script:
#    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=$SONAR_TOKEN
#  allow_failure: true

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar


create_version:
  stage: create_version

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - scp -i $DEPLOY_SSH_KEY target/*.jar user@your-server:/path/to/deploy/
    - ssh -i $DEPLOY_SSH_KEY user@your-server 'systemctl restart my-java-app'
  only:
    - main

